### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by anthony-mariotti** [BlazeCodeNet/GreenCuts#3]
It would be nice to have this updated to 1.18.2 😀! Are there any plans for that?

**Comment by BlazeCodeNet** [comment]
> It would be nice to have this updated to 1.18.2 😀! Are there any plans for that?

Havent got around to 1.18.2, but 1.19.2 is out. The entire project has been moved to my other account found [here](https://github.com/VenomCodeDev/GreenCuts)
